#!/usr/bin/env python3
"""Puts the EPSG database inside the package, ready for the wheel to be built.

The database is not versioned in this repository: it is IOGP's data, obtained either from the
`epsg-data` release of this project or built from the official EPSG SQL scripts with
tools/epsg-sqlite. This script takes one of those, copies it into the package and writes the
version file the wheel takes its version number from.

    python fetch.py --from-file /path/to/epsg.sqlite
    python fetch.py --url https://github.com/digi21/crskit/releases/download/epsg-data/epsg-v12.057.sqlite

The package version is the EPSG dataset version, read from the database itself (epsg_versionhistory),
so `pip install crskit-epsg==12.57` asks for a known EPSG release rather than an opaque number.
"""

import argparse
import shutil
import sqlite3
import urllib.request
from pathlib import Path

PACKAGE = Path(__file__).parent / "crskit_epsg"


def epsg_version(database: Path) -> str:
    """The EPSG dataset version the database was built from, e.g. '12.057'."""
    with sqlite3.connect(f"file:{database}?mode=ro", uri=True) as connection:
        row = connection.execute(
            "SELECT version_number FROM epsg_versionhistory ORDER BY version_date DESC LIMIT 1"
        ).fetchone()

    if not row or not row[0]:
        raise SystemExit(f"{database} does not look like an EPSG database (no version history).")

    return str(row[0])


def package_version(version: str) -> str:
    """'12.057' -> '12.57': the same release, spelled the way PEP 440 wants it."""
    major, _, minor = version.partition(".")
    return f"{int(major)}.{int(minor)}" if minor else str(int(major))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--from-file", type=Path, help="an EPSG SQLite database already on disk")
    source.add_argument("--url", help="download the database from this URL")
    arguments = parser.parse_args()

    destination = PACKAGE / "epsg.sqlite"

    if arguments.from_file:
        shutil.copyfile(arguments.from_file, destination)
    else:
        print(f"Downloading {arguments.url}")
        urllib.request.urlretrieve(arguments.url, destination)

    dataset = epsg_version(destination)
    version = package_version(dataset)

    (PACKAGE / "_version.py").write_text(
        '# Generated by fetch.py from the EPSG database itself. Not versioned.\n'
        f'EPSG_VERSION = "{dataset}"\n'
        f'__version__ = "{version}"\n',
        encoding="utf-8",
    )

    size = destination.stat().st_size / 1024 / 1024
    print(f"EPSG dataset {dataset} ({size:.1f} MB) -> crskit-epsg {version}")


if __name__ == "__main__":
    main()
